### ISSUE TITLE
Hard Coded field names

### ISSUE THREAD

**Issue by TycTak** [clarkj93/WordCheck#13]
A suggestion to tackling the hard coded column names is use an enum in the class and I'm sure you can get the enum "name" from an enum value. Also further down in this code you can use the actual enum value instead of row[0], row[1], row[2].

https://github.com/clarkj93/WordCheck/blob/0a875d5d433c0c4edf48e51260cfaba0fd548a4e/WordCheck/WordCheck/Extensions.cs#L15

**Comment by clarkj93** [comment]
Good suggestion. I will look into a solution along these lines and report back.
