### ISSUE TITLE
Is CSTOR needed

### ISSUE THREAD

**Issue by TycTak** [clarkj93/WordCheck#18]
Do you actually need constructor? Isn't it simply used by default.

https://github.com/clarkj93/WordCheck/blob/0a875d5d433c0c4edf48e51260cfaba0fd548a4e/WordCheck/WordCheck/Data/Profanity.cs#L11

**Comment by clarkj93** [comment]
Constructor is here because there is a constructor which requires parameters. When that is the case all constructors must be explicity written, a blank constructor is no longer a default.
